// src/components/BookSpine.tsx
import { useRef, useEffect, useState } from 'react'
import type { Book } from '../data/mockLibrary'

interface Props {
  book: Book
  dimmed: boolean
  pulled: boolean
  siblingPulled: boolean
  pullDirection: 'left' | 'right' | null
  isMobile: boolean
  onPull: (book: Book) => void
  onReturn: () => void
  onRead: (book: Book) => void
}

export default function BookSpine({ book, dimmed, pulled, siblingPulled, pullDirection, isMobile, onPull, onReturn, onRead }: Props) {
  const ref = useRef<HTMLDivElement>(null)
  const [hover, setHover] = useState(false)

  useEffect(() => {
    const el = ref.current
    if (!el) return
    if (pulled) {
      el.style.transform = isMobile
        ? 'translateZ(60px) scale(1.12) rotateY(-4deg) rotateZ(0deg)'
        : 'translateZ(80px) scale(1.15) rotateY(-5deg) rotateZ(0deg)'
      el.style.filter = 'brightness(1.2)'
      el.style.opacity = '1'
    } else if (siblingPulled && pullDirection) {
      const shift = pullDirection === 'left' ? (isMobile ? -12 : -16) : (isMobile ? 12 : 16)
      el.style.transform = `translateX(${shift}px) translateZ(-8px) rotateZ(${book.tilt}deg)`
      el.style.filter = 'brightness(0.75)'
      el.style.opacity = '0.85'
    } else if (dimmed) {
      el.style.transform = `rotateZ(${book.tilt}deg)`
      el.style.filter = 'brightness(0.7)'
      el.style.opacity = '0.85'
    } else {
      el.style.transform = `rotateZ(${book.tilt}deg)`
      el.style.filter = ''
      el.style.opacity = ''
    }
  }, [pulled, siblingPulled, pullDirection, dimmed, book.tilt, isMobile])

  const handleEnter = () => {
    if (dimmed || pulled || siblingPulled || isMobile) return
    setHover(true)
  }

  const handleLeave = () => {
    setHover(false)
  }

  const handleClick = () => {
    if (dimmed) return
    if (pulled) {
      onRead(book)
      return
    }
    if (siblingPulled) return
    onPull(book)
  }

  const isHover = hover && !dimmed && !pulled && !siblingPulled && !isMobile
  const width = isMobile ? book.width * 0.85 : book.width
  const height = isMobile ? book.height * 0.85 : book.height

  return (
    <div
      ref={ref}
      onMouseEnter={handleEnter}
      onMouseLeave={handleLeave}
      onClick={handleClick}
      style={{
        width,
        height,
        flexShrink: 0,
        transformStyle: 'preserve-3d',
        transform: `rotateZ(${book.tilt}deg)${isHover ? ' translateZ(16px) scale(1.05) rotateY(-3deg)' : ''}`,
        transition: 'transform 0.5s cubic-bezier(0.23,1,0.32,1), filter 0.5s ease, opacity 0.5s ease, z-index 0s',
        cursor: dimmed || siblingPulled ? 'default' : 'pointer',
        position: 'relative',
      }}
    >
      {/* Spine face */}
      <div style={{
        position: 'absolute', inset: 0,
        background: `linear-gradient(160deg, ${book.spineColor} 0%, ${book.spineDark} 100%)`,
        transform: `translateZ(${isMobile ? 4 : 5}px)`,
        overflow: 'hidden',
        boxShadow: pulled
          ? '6px 0 20px rgba(0,0,0,0.7), 0 0 30px rgba(212,160,85,0.15), inset -5px 0 12px rgba(0,0,0,0.35), inset 3px 0 6px rgba(255,255,255,0.06)'
          : isHover
          ? '4px 0 14px rgba(0,0,0,0.6), 0 0 20px rgba(212,160,85,0.12), inset -5px 0 12px rgba(0,0,0,0.35), inset 3px 0 6px rgba(255,255,255,0.06)'
          : '3px 0 10px rgba(0,0,0,0.55), inset -5px 0 12px rgba(0,0,0,0.35), inset 3px 0 6px rgba(255,255,255,0.06)',
        transition: 'box-shadow 0.5s ease',
      }}>
        {/* Gold top edge */}
        <div style={{
          position: 'absolute', top: 0, left: 0, right: 0, height: isMobile ? 2 : 3,
          background: 'linear-gradient(90deg, transparent 6%, #c9a44a 22%, #f0d98c 42%, #c9a44a 62%, transparent 94%)',
          opacity: pulled ? 0.9 : 0.75,
        }} />
        {/* Gold bottom edge */}
        <div style={{
          position: 'absolute', bottom: 0, left: 0, right: 0, height: isMobile ? 2 : 3,
          background: 'linear-gradient(90deg, transparent 6%, #c9a44a 22%, #f0d98c 42%, #c9a44a 62%, transparent 94%)',
          opacity: pulled ? 0.9 : 0.75,
        }} />
        {/* Shine - simplified on mobile */}
        <div style={{
          position: 'absolute', inset: 0,
          background: isMobile
            ? 'linear-gradient(115deg, rgba(255,255,255,0.08) 0%, transparent 50%, transparent 50%, rgba(255,255,255,0.02) 100%)'
            : pulled
            ? 'linear-gradient(115deg, rgba(255,255,255,0.18) 0%, transparent 35%, transparent 65%, rgba(255,255,255,0.05) 100%)'
            : 'linear-gradient(115deg, rgba(255,255,255,0.12) 0%, transparent 35%, transparent 65%, rgba(255,255,255,0.03) 100%)',
          pointerEvents: 'none',
        }} />
        {/* Texture lines - hidden on mobile */}
        {!isMobile && (
          <div style={{
            position: 'absolute', inset: 0, opacity: 0.25,
            backgroundImage: 'repeating-linear-gradient(90deg, transparent, transparent 1px, rgba(0,0,0,0.05) 1px, rgba(0,0,0,0.05) 2px)',
            pointerEvents: 'none',
          }} />
        )}
        {/* Title + Author */}
        <div style={{
          position: 'absolute', inset: 0,
          display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center',
          padding: isMobile ? '14px 2px' : '18px 3px',
          gap: isMobile ? 10 : 14,
        }}>
          <span style={{
            writingMode: 'vertical-rl', textOrientation: 'mixed',
            color: 'rgba(255,255,255,0.5)', fontSize: isMobile ? 8 : 9,
            letterSpacing: isMobile ? 1.5 : 2,
            maxHeight: isMobile ? 40 : 50, overflow: 'hidden',
          }}>{book.author}</span>
          <span style={{
            writingMode: 'vertical-rl', textOrientation: 'mixed',
            color: 'rgba(255,255,255,0.92)', fontSize: isMobile ? 11 : 13,
            fontWeight: 700,
            letterSpacing: isMobile ? 2 : 3, lineHeight: 1.3,
            maxHeight: isMobile ? 100 : 130, overflow: 'hidden',
            textShadow: '0 1px 3px rgba(0,0,0,0.6)',
          }}>{book.title}</span>
        </div>
        {/* Pulled glow border */}
        {pulled && (
          <div style={{
            position: 'absolute', inset: -2,
            border: '1.5px solid rgba(212,160,85,0.35)',
            boxShadow: '0 0 18px rgba(212,160,85,0.2), inset 0 0 10px rgba(212,160,85,0.06)',
            pointerEvents: 'none',
          }} />
        )}
      </div>
      {/* Page edges */}
      <div style={{
        position: 'absolute', top: 0, width: isMobile ? 7 : 9, height: '100%',
        right: isMobile ? -4 : -5,
        background: 'linear-gradient(90deg, #e8e0c8, #f5eed8 35%, #e8e0c8)',
        transformOrigin: 'left center',
        transform: 'rotateY(90deg)',
        boxShadow: isMobile ? 'none' : 'inset 0 0 5px rgba(0,0,0,0.12)',
      }} />
      {/* Bottom edge */}
      <div style={{
        position: 'absolute', left: 0, right: 0, height: isMobile ? 5 : 7,
        bottom: isMobile ? -3 : -4,
        background: 'linear-gradient(90deg, rgba(20,14,8,0.8), rgba(30,20,12,0.65) 50%, rgba(20,14,8,0.8))',
        transformOrigin: 'top center',
        transform: 'rotateX(90deg)',
      }} />
    </div>
  )
}

// src/components/BookSpine.vue
<template>
  <div
    class="book-spine"
    :style="spineStyle"
    :class="{ 'is-recent': isRecent }"
  >
    <div class="spine-inner">
      <span class="spine-title">{{ book.title }}</span>
      <span class="spine-author">{{ book.author }}</span>
    </div>
    <div v-if="isRecent" class="recent-badge">最近</div>
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue'
import type { Book } from '../data/books'

const props = defineProps<{
  book: Book
  isRecent?: boolean
}>()

const spineStyle = computed(() => ({
  backgroundColor: props.book.spineColor,
  boxShadow: 'inset -4px 0 8px rgba(0,0,0,0.3), inset 2px 0 4px rgba(255,255,255,0.1)'
}))
</script>

<style scoped>
.book-spine {
  flex-shrink: 0;
  width: 42px;
  height: 180px;
  border-radius: 2px 4px 4px 2px;
  cursor: pointer;
  position: relative;
  transition: transform 0.2s ease, box-shadow 0.2s ease;
  transform-origin: center bottom;
}

.book-spine:hover {
  transform: translateY(-8px) scale(1.05);
  box-shadow: 0 8px 20px rgba(0,0,0,0.5);
  z-index: 10;
}

.book-spine:active {
  transform: translateY(-4px) scale(1.02);
}

.spine-inner {
  width: 100%;
  height: 100%;
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
  padding: 8px 2px;
  overflow: hidden;
}

.spine-title {
  writing-mode: vertical-rl;
  text-orientation: mixed;
  color: rgba(255,255,255,0.9);
  font-size: 13px;
  font-weight: 600;
  letter-spacing: 2px;
  text-shadow: 0 1px 2px rgba(0,0,0,0.5);
  line-height: 1.4;
  max-height: 140px;
  overflow: hidden;
  text-overflow: ellipsis;
}

.spine-author {
  writing-mode: vertical-rl;
  text-orientation: mixed;
  color: rgba(255,255,255,0.6);
  font-size: 10px;
  margin-top: 8px;
  max-height: 60px;
  overflow: hidden;
}

.is-recent {
  border: 2px solid var(--accent);
}

.recent-badge {
  position: absolute;
  top: -8px;
  right: -4px;
  background: var(--accent);
  color: #1a1410;
  font-size: 9px;
  font-weight: 700;
  padding: 2px 6px;
  border-radius: 8px;
  box-shadow: 0 2px 4px rgba(0,0,0,0.3);
}
</style>
